---
title: "Example Sleuth Analysis"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

# Overview

We have adapted the [sleuth walkthrough tutorial][walkthru] so that we can show
how to analyze the datasets that were generated by the staff prior to the start
of this workshop.

[walkthru]: https://pachterlab.github.io/sleuth_walkthroughs/trapnell/analysis.html

# Data Retrieval

By now, you have processed each of the FASTQ files generated by each sample
using Kallisto. This will provide you with an output directory per sample
that has data (counts and other metadata) that Kallisto will use for downstream
processing.

We have also processed these data and made them available to you. In order to
get the kallisto results for all of these data, you can use the `aws s3 sync`
command provided below. Note that this will download ~ 8.2Gb of data to your
computer / Amazon instance.

```bash
cd /data
aws s3 sync s3://mbl.data/mapping/may may-kallisto
```

You will now have a directory structure that looks like this:

```bash
/data/may-kallisto
├── fish/
│   ├── drdgwt01/
│   │   ├── abundance.h5
│   │   ├── abundance.tsv
│   │   ├── kallisto.log
│   │   ├── pseudoalignments.bam
│   │   ├── pseudoalignments.bam.bai
│   │   └── run_info.json
│   ├── drdgwt02/
│   ├── ...
│   └── drkrwt15/
├── fly/
│   ├── dmneaohi01/
│   ├── ...
│   └── dmnewthi12/
├── mouse/
│   ├── mmchko02/
│   ├── ...
│   └── mmwpwt04/
┴
```

Which should be somewhat similar to the directory structure you generated
manually.

# Data Setup

We 